import type { Locale } from "@/lib/i18n";

export type CareersUi = {
  title: string;
  intro: string;
  introSecond: string;
  roles: string;
  open: string;
  comingSoon: string;
  notForYou: string;
  notForYouItems: string[];
  stillReading: string;
  process: string;
  processIntro: string;
  processSteps: string[];
  processClosing: string;
  testimonial: string;
  testimonialLink: string;
  howWeWork: string;
  howWeWorkItems: string[];
  stayClose: string;
  sundayLog: string;
  subscribe: string;
  back: string;
  home: string;
  applyingFor: string;
  applyTitle: string;
  applyIntro: string;
  careers: string;
};

export const careersUi: Record<Locale, CareersUi> = {
  en: {
    title: "Build with me.", intro: "I'm building Payle, the money layer for AI agents. I hire by artifact, not by title.", introSecond: "Ship something real, then we talk.", roles: "Roles", open: "open", comingSoon: "coming soon", notForYou: "We're probably not for you if", notForYouItems: ["You want a big salary before there's a product with users. We're pre-seed: the equity is the bet, and it's a real one.", "You need tickets, sprints and a manager checking your hours. We're objective-based. Self-driven or struggling.", "You think AI in the payment path is fine \"because it's smart enough.\" We have a law about it. We won't debate it.", "You're here for the title. The code does the talking here: including for the CEO."], stillReading: "Still reading? Then we're probably for you.", process: "The hiring process", processIntro: "Every step, no surprises. Total time: 2-3 weeks from application to offer.", processSteps: ["Artifact challenge (paid, one week): you ship a real task on our real contract. We pay for your time; you keep the work.", "Written review: we review your submission against our test suite. You get the written verdict either way. No silent rejections.", "Founder call (30 min): commitment, compensation, your questions. Real answers, including the doubts.", "Offer with papers: salary, equity, vesting, cliff. In writing the same day as the verbal."], processClosing: "If we ever stop responding at a step, we've failed: hold us to it.", testimonial: "Don't take my word for it: read how Alex joined:", testimonialLink: "Welcoming Alex Mwaniki →", howWeWork: "How we work", howWeWorkItems: ["Remote-first, async-first. The team is distributed. Written communication is our primary format: Friday demo is our only fixed ritual.", "Objectives over hours. We don't count time. We count shipped, verified work: weekly, visible to everyone.", "No LLM in the money path. Ever. AI plans and advises. Deterministic code decides where money moves. If you join, you inherit this law and help defend it.", "Honesty is the product. We publish our failures, our audit findings, our doubts. If that's uncomfortable, we're the wrong company."], stayClose: "Stay close to the work", sundayLog: "Follow the work in the Sunday log.", subscribe: "Subscribe to the Sunday log →", back: "Back to careers", home: "Home", applyingFor: "Applying for", applyTitle: "Build the artifact first.", applyIntro: "The form asks about the thing you built, the decisions inside it, and why this work matters to you.", careers: "Careers",
  },
  it: {
    title: "Costruisci con me.", intro: "Sto costruendo Payle, il money layer per gli agenti AI. Scelgo le persone dagli artefatti, non dai titoli.", introSecond: "Costruisci qualcosa di reale, poi parliamo.", roles: "Ruoli", open: "aperti", comingSoon: "in arrivo", notForYou: "Probabilmente non facciamo per te se", notForYouItems: ["Vuoi uno stipendio alto prima che esista un prodotto con utenti. Siamo pre-seed: l'equity è la scommessa, ed è reale.", "Hai bisogno di ticket, sprint e di un manager che controlli le tue ore. Lavoriamo per obiettivi. O sei autonomo o fai fatica.", "Pensi che l'AI nel percorso di pagamento vada bene perché è abbastanza intelligente. Abbiamo una regola. Non la mettiamo in discussione.", "Sei qui per il titolo. Qui parla il codice, anche per il CEO."], stillReading: "Stai ancora leggendo? Allora probabilmente facciamo per te.", process: "Il processo di selezione", processIntro: "Ogni passaggio, senza sorprese. Tempo totale: 2-3 settimane dalla candidatura all'offerta.", processSteps: ["Challenge sull'artefatto (pagata, una settimana): costruisci un task reale sul nostro contratto. Paghiamo il tuo tempo; il lavoro resta tuo.", "Revisione scritta: valutiamo la consegna con la nostra suite di test. Ricevi un verdetto scritto comunque. Nessun rifiuto silenzioso.", "Call con il founder (30 min): impegno, compenso e le tue domande. Risposte reali, anche sui dubbi.", "Offerta con documenti: stipendio, equity, vesting e cliff. Tutto per iscritto lo stesso giorno."], processClosing: "Se smettiamo di rispondere a un passaggio, abbiamo fallito: chiedici conto.", testimonial: "Non fidarti solo della mia parola: leggi come è entrato Alex:", testimonialLink: "Welcoming Alex Mwaniki →", howWeWork: "Come lavoriamo", howWeWorkItems: ["Prima remoto, prima asincrono. Il team è distribuito. La comunicazione scritta è il formato principale; la demo del venerdì è l'unico rituale fisso.", "Obiettivi, non ore. Non contiamo il tempo. Contiamo lavoro spedito e verificato, ogni settimana, visibile a tutti.", "Nessun LLM nel percorso del denaro. Mai. L'AI pianifica e consiglia. Il codice deterministico decide dove si muove il denaro. Se entri, erediti questa regola e contribuisci a difenderla.", "L'onestà è il prodotto. Pubblichiamo fallimenti, risultati dell'audit e dubbi. Se ti mette a disagio, non siamo l'azienda giusta."], stayClose: "Resta vicino al lavoro", sundayLog: "Segui il lavoro nel Sunday log.", subscribe: "Iscriviti al Sunday log →", back: "Torna alle careers", home: "Home", applyingFor: "Candidatura per", applyTitle: "Costruisci prima l'artefatto.", applyIntro: "Il form chiede cosa hai costruito, le decisioni che contiene e perché questo lavoro conta per te.", careers: "Lavora con me",
  },
  fr: {
    title: "Construisez avec moi.", intro: "Je construis Payle, la couche financière des agents IA. Je recrute sur les artefacts, pas sur les titres.", introSecond: "Livrez quelque chose de réel, puis parlons.", roles: "Postes", open: "ouverts", comingSoon: "bientôt", notForYou: "Nous ne sommes probablement pas faits pour vous si", notForYouItems: ["Vous voulez un gros salaire avant qu'il y ait un produit avec des utilisateurs. Nous sommes en pré-seed : l'equity est le pari.", "Vous avez besoin de tickets, de sprints et d'un manager qui vérifie vos heures. Nous travaillons par objectifs.", "Vous pensez que l'IA peut décider sur le chemin du paiement parce qu'elle est assez intelligente. Nous avons une règle non négociable.", "Vous êtes là pour le titre. Ici, le code parle, y compris pour le CEO."], stillReading: "Vous lisez encore ? Alors nous sommes probablement faits pour vous.", process: "Le processus de recrutement", processIntro: "Chaque étape, sans surprise. Durée totale : 2 à 3 semaines, de la candidature à l'offre.", processSteps: ["Challenge d'artefact (rémunéré, une semaine): vous livrez une tâche réelle sur notre contrat. Nous payons votre temps et vous gardez le travail.", "Revue écrite: nous évaluons votre travail avec notre suite de tests. Vous recevez un verdict écrit dans tous les cas.", "Appel avec le fondateur (30 min): engagement, rémunération et questions. Des réponses réelles, y compris les doutes.", "Offre écrite: salaire, equity, vesting et cliff. Par écrit le jour même."], processClosing: "Si nous cessons de répondre à une étape, nous avons échoué : rappelez-le-nous.", testimonial: "Ne me croyez pas sur parole : découvrez comment Alex nous a rejoints :", testimonialLink: "Welcoming Alex Mwaniki →", howWeWork: "Notre façon de travailler", howWeWorkItems: ["Remote et asynchrone par défaut. L'équipe est distribuée. L'écrit est notre format principal ; la démo du vendredi est notre seul rituel fixe.", "Les objectifs plutôt que les heures. Nous comptons le travail livré et vérifié, chaque semaine, visible par tous.", "Aucun LLM dans le chemin de l'argent. Jamais. L'IA planifie et conseille. Le code déterministe décide où va l'argent.", "L'honnêteté est le produit. Nous publions nos échecs, nos audits et nos doutes. Si cela vous gêne, nous ne sommes pas faits pour vous."], stayClose: "Restez proche du travail", sundayLog: "Suivez le travail dans le Sunday log.", subscribe: "S'inscrire au Sunday log →", back: "Retour aux carrières", home: "Accueil", applyingFor: "Candidature pour", applyTitle: "Construisez d'abord l'artefact.", applyIntro: "Le formulaire porte sur ce que vous avez construit, les décisions prises et pourquoi ce travail compte pour vous.", careers: "Carrières",
  },
  es: {
    title: "Construye conmigo.", intro: "Estoy construyendo Payle, la capa de dinero para agentes de IA. Contrato por artefactos, no por títulos.", introSecond: "Construye algo real y después hablamos.", roles: "Puestos", open: "abiertos", comingSoon: "próximamente", notForYou: "Probablemente no somos para ti si", notForYouItems: ["Quieres un gran salario antes de que exista un producto con usuarios. Estamos en pre-seed: la equity es la apuesta.", "Necesitas tickets, sprints y un manager que controle tus horas. Trabajamos por objetivos.", "Crees que la IA puede decidir en el recorrido del pago porque es suficientemente inteligente. Tenemos una regla.", "Vienes por el título. Aquí habla el código, incluido el del CEO."], stillReading: "¿Sigues leyendo? Entonces probablemente somos para ti.", process: "El proceso de selección", processIntro: "Cada paso, sin sorpresas. Tiempo total: 2-3 semanas desde la candidatura hasta la oferta.", processSteps: ["Reto de artefacto (pagado, una semana): entregas una tarea real sobre nuestro contrato. Pagamos tu tiempo y conservas el trabajo.", "Revisión escrita: revisamos tu entrega con nuestra suite de tests. Recibes un veredicto escrito en cualquier caso.", "Llamada con el fundador (30 min): compromiso, compensación y tus preguntas. Respuestas reales, también sobre las dudas.", "Oferta por escrito: salario, equity, vesting y cliff. Por escrito el mismo día."], processClosing: "Si dejamos de responder en algún paso, hemos fallado: pídenos cuentas.", testimonial: "No te fíes solo de mi palabra: lee cómo se unió Alex:", testimonialLink: "Welcoming Alex Mwaniki →", howWeWork: "Cómo trabajamos", howWeWorkItems: ["Remoto y asíncrono por defecto. El equipo está distribuido. La comunicación escrita es nuestro formato principal; la demo del viernes es el único ritual fijo.", "Objetivos antes que horas. Contamos el trabajo entregado y verificado, cada semana, visible para todos.", "No hay LLM en el recorrido del dinero. Nunca. La IA planifica y aconseja. El código determinista decide dónde se mueve el dinero.", "La honestidad es el producto. Publicamos nuestros fallos, auditorías y dudas. Si incomoda, no somos la empresa adecuada."], stayClose: "Sigue cerca del trabajo", sundayLog: "Sigue el trabajo en el Sunday log.", subscribe: "Suscribirse al Sunday log →", back: "Volver a carreras", home: "Inicio", applyingFor: "Candidatura para", applyTitle: "Construye primero el artefacto.", applyIntro: "El formulario pregunta por lo que construiste, tus decisiones y por qué este trabajo te importa.", careers: "Carreras",
  },
  de: {
    title: "Baue mit mir.", intro: "Ich entwickle Payle, die Geldschicht für KI-Agenten. Ich stelle nach Artefakten ein, nicht nach Titeln.", introSecond: "Baue etwas Reales, dann sprechen wir.", roles: "Rollen", open: "offen", comingSoon: "bald verfügbar", notForYou: "Wir passen wahrscheinlich nicht zu dir, wenn", notForYouItems: ["Du ein großes Gehalt willst, bevor es ein Produkt mit Nutzern gibt. Wir sind Pre-Seed: Equity ist die Wette.", "Du Tickets, Sprints und einen Manager brauchst, der deine Stunden prüft. Wir arbeiten zielorientiert.", "Du glaubst, KI könne den Zahlungsweg entscheiden, weil sie klug genug sei. Wir haben eine feste Regel.", "Du wegen des Titels hier bist. Hier spricht der Code, auch beim CEO."], stillReading: "Du liest noch? Dann passen wir wahrscheinlich zu dir.", process: "Der Einstellungsprozess", processIntro: "Jeder Schritt ohne Überraschungen. Insgesamt 2–3 Wochen von der Bewerbung bis zum Angebot.", processSteps: ["Artefakt-Challenge (bezahlt, eine Woche): du baust eine echte Aufgabe auf unserem Vertrag. Wir bezahlen deine Zeit, du behältst die Arbeit.", "Schriftliche Prüfung: wir prüfen deine Abgabe mit unserer Testsuite. Du erhältst in jedem Fall ein schriftliches Urteil.", "Gründer-Gespräch (30 Min.): Einsatz, Vergütung und deine Fragen. Echte Antworten, auch zu Zweifeln.", "Schriftliches Angebot: Gehalt, Equity, Vesting und Cliff. Noch am selben Tag schriftlich."], processClosing: "Wenn wir an einem Schritt nicht mehr antworten, haben wir versagt. Halte uns daran.", testimonial: "Verlass dich nicht nur auf mein Wort: Lies, wie Alex dazukam:", testimonialLink: "Welcoming Alex Mwaniki →", howWeWork: "Wie wir arbeiten", howWeWorkItems: ["Remote und asynchron zuerst. Das Team ist verteilt. Schriftliche Kommunikation ist unser Hauptformat; die Freitagsdemo ist unser einziges festes Ritual.", "Ziele statt Stunden. Wir zählen gelieferte und verifizierte Arbeit, jede Woche für alle sichtbar.", "Kein LLM im Geldweg. Niemals. KI plant und berät. Deterministischer Code entscheidet, wohin sich Geld bewegt.", "Ehrlichkeit ist das Produkt. Wir veröffentlichen Fehler, Audits und Zweifel. Wenn das unangenehm ist, passen wir nicht zusammen."], stayClose: "Bleib nah an der Arbeit", sundayLog: "Verfolge die Arbeit im Sunday log.", subscribe: "Zum Sunday log →", back: "Zurück zu Karriere", home: "Startseite", applyingFor: "Bewerbung für", applyTitle: "Baue zuerst das Artefakt.", applyIntro: "Das Formular fragt nach dem, was du gebaut hast, den Entscheidungen darin und warum diese Arbeit dir wichtig ist.", careers: "Karriere",
  },
};
