import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import CopyEmail from "@/components/CopyEmail";
import MilanClock from "@/components/MilanClock";
import { ChevronRight } from "@/components/icons";
import { copy, LOCALES, isLocale, type Locale } from "@/lib/i18n";
import { site } from "@/lib/site";
import { socialImages } from "@/lib/social";
import { languageAlternates } from "@/lib/seo";
import { posts } from "@/lib/posts";
import { notes } from "@/lib/notes";
import { feedback } from "@/lib/feedback";
import { FeedbackModalButton } from "@/components/FeedbackForm";
import { LocalizedSection } from "@/components/LocalizedSection";
import { NewsletterSection } from "@/components/NewsletterSection";
import { uiCopy } from "@/lib/i18n-ui";

const SECTIONS = ["about", "work", "thoughts", "notes", "feedback", "privacy", "terms", "cookies", "legal", "newsletter", "link", "voice-notes", "videos"] as const;
type Section = (typeof SECTIONS)[number];

type HomeCopy = {
  who: string; whoBody: string; whoBody2: string; principles: string; principleItems: [string, string][];
  now: string; nowBody: string; projects: string; payle: string; payleBody: string; thoughtsBody: string;
  notesBody: string; feedbackBody: string; fieldNotes: string; fieldBody: string; voice: string; voiceBody: string; videos: string; videosBody: string;
};

const homeCopy: Record<Locale, HomeCopy> = {
  en: { who: "Who is Mattia Ciuni?", whoBody: "Mattia Ciuni is an Italian founder and the founder and CEO of Payle, a company building the money layer for AI agents. He works on the rules, authorization and receipts that let software spend money safely on behalf of people.", whoBody2: "What does Mattia Ciuni do? Before Payle, he built Celeste, an AI browser. Today his work sits at the intersection of AI agents, payments infrastructure, fintech and software engineering.", principles: "Principles", principleItems: [["Build the hard part first.", "Everyone ships the demo; the money path is where products die. I start where the risk lives."], ["Verification over vibes.", "If a claim cannot survive an audit, a test, or a skeptical engineer, it does not go on the internet. Including this site."], ["Small teams, heavy leverage.", "AI tools multiplied my output; discipline multiplied the AI. Two people with tests beat ten with meetings."], ["The best ideas survive attack.", "I post my architecture before I have a pitch. What survives the comments is what gets built."]], now: "Now", nowBody: "Building the money layer for AI agents at Payle. Applying to YC, relocating to San Francisco.", projects: "Projects", payle: "The money layer for AI agents.", payleBody: "Notes on AI agents and building Payle.", thoughtsBody: "Thoughts on AI agents and building Payle.", notesBody: "Longer, slower pieces on the systems, people and ideas behind the work.", feedbackBody: "Engineers attack Payle's architecture in public. I publish what their attacks changed, corrections included.", fieldNotes: "Field notes", fieldBody: "Some things are better heard. Some are better seen. I am making room for both.", voice: "Voice Notes", voiceBody: "Unedited thoughts, spoken before they become essays.", videos: "Videos", videosBody: "A visual log of building, thinking and changing my mind." },
  it: { who: "Chi è Mattia Ciuni?", whoBody: "Mattia Ciuni è un founder italiano e il founder e CEO di Payle, una società che costruisce il money layer per gli agenti AI. Lavora su regole, autorizzazione e ricevute che permettono al software di spendere per conto delle persone in modo sicuro.", whoBody2: "Cosa fa Mattia Ciuni? Prima di Payle ha costruito Celeste, un browser AI. Oggi il suo lavoro unisce agenti AI, infrastruttura dei pagamenti, fintech e ingegneria del software.", principles: "Principi", principleItems: [["Costruisci prima la parte difficile.", "Tutti spediscono la demo; è il percorso del denaro dove i prodotti muoiono. Io inizio dal rischio."], ["Verifica, non sensazioni.", "Se un'affermazione non supera un audit, un test o un ingegnere scettico, non finisce online. Nemmeno su questo sito."], ["Piccoli team, grande leva.", "Gli strumenti AI hanno moltiplicato il mio output; la disciplina ha moltiplicato l'AI. Due persone con test battono dieci persone in riunione."], ["Le idee migliori resistono agli attacchi.", "Pubblico la mia architettura prima del pitch. Ciò che resiste ai commenti è ciò che costruiamo."]], now: "Ora", nowBody: "Costruisco il money layer per gli agenti AI in Payle. Sto facendo application a YC e mi trasferirò a San Francisco.", projects: "Progetti", payle: "Il money layer per gli agenti AI.", payleBody: "Note su agenti AI e sulla costruzione di Payle.", thoughtsBody: "Pensieri su agenti AI e sulla costruzione di Payle.", notesBody: "Testi più lunghi e lenti sui sistemi, sulle persone e sulle idee dietro il lavoro.", feedbackBody: "Gli ingegneri attaccano pubblicamente l'architettura di Payle. Pubblico ciò che i loro attacchi hanno cambiato, correzioni incluse.", fieldNotes: "Note di campo", fieldBody: "Alcune cose si ascoltano meglio. Altre si vedono meglio. Sto facendo spazio a entrambe.", voice: "Note vocali", voiceBody: "Pensieri non editati, parlati prima di diventare saggi.", videos: "Video", videosBody: "Un diario visivo del lavoro, del pensiero e dei cambi di idea." },
  fr: { who: "Qui est Mattia Ciuni ?", whoBody: "Mattia Ciuni est un fondateur italien et le fondateur et CEO de Payle, une entreprise qui construit la couche financière des agents IA. Il travaille sur les règles, l'autorisation et les reçus qui permettent aux logiciels de dépenser pour les personnes en sécurité.", whoBody2: "Que fait Mattia Ciuni ? Avant Payle, il a créé Celeste, un navigateur IA. Aujourd'hui son travail relie agents IA, infrastructure des paiements, fintech et ingénierie logicielle.", principles: "Principes", principleItems: [["Construire d'abord la partie difficile.", "Tout le monde livre la démo ; c'est le parcours de l'argent qui fait mourir les produits. Je commence par le risque."], ["Vérifier plutôt que croire.", "Une affirmation qui ne résiste pas à un audit, un test ou un ingénieur sceptique ne va pas sur internet. Pas même ici."], ["Petites équipes, grand effet de levier.", "Les outils IA ont multiplié ma production ; la discipline a multiplié l'IA. Deux personnes avec des tests valent mieux que dix réunions."], ["Les meilleures idées résistent aux attaques.", "Je publie mon architecture avant le pitch. Ce qui résiste aux commentaires est ce qui est construit."]], now: "Maintenant", nowBody: "Je construis la couche financière des agents IA chez Payle. Candidature à YC et départ prochain pour San Francisco.", projects: "Projets", payle: "La couche financière des agents IA.", payleBody: "Réflexions sur les agents IA et la construction de Payle.", thoughtsBody: "Réflexions sur les agents IA et la construction de Payle.", notesBody: "Des textes plus longs sur les systèmes, les personnes et les idées derrière le travail.", feedbackBody: "Des ingénieurs attaquent publiquement l'architecture de Payle. Je publie ce que leurs critiques ont changé, corrections comprises.", fieldNotes: "Notes de terrain", fieldBody: "Certaines choses s'écoutent mieux. D'autres se voient mieux. Je fais de la place aux deux.", voice: "Notes vocales", voiceBody: "Des pensées non retouchées, dites avant de devenir des essais.", videos: "Vidéos", videosBody: "Un journal visuel de la construction, de la réflexion et des changements d'avis." },
  es: { who: "¿Quién es Mattia Ciuni?", whoBody: "Mattia Ciuni es un fundador italiano y el fundador y CEO de Payle, una empresa que construye la capa de dinero para agentes de IA. Trabaja en reglas, autorización y recibos que permiten al software gastar de forma segura en nombre de las personas.", whoBody2: "¿Qué hace Mattia Ciuni? Antes de Payle construyó Celeste, un navegador de IA. Hoy su trabajo une agentes de IA, infraestructura de pagos, fintech e ingeniería de software.", principles: "Principios", principleItems: [["Construir primero la parte difícil.", "Todos lanzan la demo; el camino del dinero es donde mueren los productos. Empiezo por el riesgo."], ["Verificar, no confiar en sensaciones.", "Si una afirmación no supera una auditoría, una prueba o a un ingeniero escéptico, no llega a internet. Tampoco aquí."], ["Equipos pequeños, gran impacto.", "Las herramientas de IA multiplicaron mi producción; la disciplina multiplicó la IA. Dos personas con pruebas vencen a diez en reuniones."], ["Las mejores ideas resisten los ataques.", "Publico mi arquitectura antes del pitch. Lo que resiste los comentarios es lo que construimos."]], now: "Ahora", nowBody: "Construyo la capa de dinero para agentes de IA en Payle. Solicitud a YC y traslado a San Francisco.", projects: "Proyectos", payle: "La capa de dinero para agentes de IA.", payleBody: "Notas sobre agentes de IA y la construcción de Payle.", thoughtsBody: "Ideas sobre agentes de IA y la construcción de Payle.", notesBody: "Textos más largos sobre los sistemas, las personas y las ideas detrás del trabajo.", feedbackBody: "Los ingenieros atacan públicamente la arquitectura de Payle. Publico lo que sus críticas han cambiado, con las correcciones incluidas.", fieldNotes: "Notas de campo", fieldBody: "Algunas cosas se escuchan mejor. Otras se ven mejor. Estoy haciendo espacio para ambas.", voice: "Notas de voz", voiceBody: "Pensamientos sin editar, hablados antes de convertirse en ensayos.", videos: "Vídeos", videosBody: "Un diario visual de construir, pensar y cambiar de opinión." },
  de: { who: "Wer ist Mattia Ciuni?", whoBody: "Mattia Ciuni ist ein italienischer Gründer und Gründer und CEO von Payle, einem Unternehmen, das die Geldschicht für KI-Agenten entwickelt. Er arbeitet an Regeln, Autorisierung und Belegen, mit denen Software sicher im Namen von Menschen ausgeben kann.", whoBody2: "Was macht Mattia Ciuni? Vor Payle entwickelte er Celeste, einen KI-Browser. Heute verbindet seine Arbeit KI-Agenten, Zahlungsinfrastruktur, Fintech und Softwareentwicklung.", principles: "Prinzipien", principleItems: [["Zuerst den schwierigen Teil bauen.", "Alle liefern die Demo; am Geldweg sterben Produkte. Ich beginne dort, wo das Risiko liegt."], ["Überprüfen statt glauben.", "Wenn eine Behauptung kein Audit, keinen Test oder einen skeptischen Ingenieur übersteht, kommt sie nicht ins Internet. Auch nicht hier."], ["Kleine Teams, große Wirkung.", "KI-Tools haben meinen Output vervielfacht; Disziplin hat die KI vervielfacht. Zwei Menschen mit Tests schlagen zehn in Meetings."], ["Die besten Ideen überstehen Angriffe.", "Ich veröffentliche meine Architektur vor dem Pitch. Was Kommentare übersteht, wird gebaut."]], now: "Jetzt", nowBody: "Ich entwickle bei Payle die Geldschicht für KI-Agenten. YC-Bewerbung und Umzug nach San Francisco.", projects: "Projekte", payle: "Die Geldschicht für KI-Agenten.", payleBody: "Notizen über KI-Agenten und den Aufbau von Payle.", thoughtsBody: "Gedanken über KI-Agenten und den Aufbau von Payle.", notesBody: "Längere Texte über die Systeme, Menschen und Ideen hinter der Arbeit.", feedbackBody: "Ingenieure greifen Payles Architektur öffentlich an. Ich veröffentliche, was ihre Kritik verändert hat, inklusive Korrekturen.", fieldNotes: "Feldnotizen", fieldBody: "Manche Dinge hört man besser. Andere sieht man besser. Ich schaffe Raum für beides.", voice: "Sprachnotizen", voiceBody: "Unbearbeitete Gedanken, gesprochen bevor sie zu Essays werden.", videos: "Videos", videosBody: "Ein visuelles Protokoll vom Bauen, Denken und Umdenken." },
};

export function generateStaticParams() {
  return LOCALES.flatMap((locale) => SECTIONS.map((slug) => ({ locale, slug })));
}

function sectionText(locale: Locale, section: Section) {
  const text = copy[locale];
  const home = homeCopy[locale];
  const content: Record<Section, { title: string; body: string }> = {
    about: { title: text.about, body: text.aboutBody }, work: { title: text.work, body: text.workBody }, thoughts: { title: text.thoughts, body: text.shortThoughts }, notes: { title: text.notes, body: text.longNotes }, feedback: { title: text.feedback, body: text.feedbackBody }, privacy: { title: text.privacy, body: locale === "it" ? "Come raccolgo, uso e proteggo i dati quando visiti questo sito." : "How this site collects, uses and protects information when you visit." }, terms: { title: text.terms, body: locale === "it" ? "Le regole che si applicano all'uso di questo sito e dei suoi contenuti." : "The rules that apply when you use this site and its public content." }, cookies: { title: text.cookies, body: locale === "it" ? "Le tecnologie di archiviazione usate da questo sito." : "The storage technologies used by this site." }, legal: { title: text.legal, body: locale === "it" ? "Documenti, contatti e informazioni legali del sito." : "Site documents, contacts and legal information." }, newsletter: { title: text.newsletter, body: locale === "it" ? "Una email a settimana: cosa ho spedito, cosa si è rotto e cosa ho deciso." : "One email a week: what I shipped, what broke and what I decided." }, link: { title: text.link, body: text.founder }, "voice-notes": { title: home.voice, body: home.voiceBody }, videos: { title: home.videos, body: home.videosBody },
  };
  return content[section];
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> {
  const { locale: raw, slug } = await params;
  if (!isLocale(raw) || !SECTIONS.includes(slug as Section)) return {};
  const item = sectionText(raw, slug as Section);
  return { title: item.title, description: item.body, alternates: { canonical: `/${raw}/${slug}/`, languages: languageAlternates(`/${slug}/`) }, openGraph: { type: "website", url: `/${raw}/${slug}/`, siteName: "Mattia Ciuni", title: item.title, description: item.body, images: socialImages("/og.png", item.title).og } };
}

export function LocalizedHome({ locale }: { locale: Locale }) {
  const text = copy[locale]; const home = homeCopy[locale]; const ui = uiCopy[locale];
  return (
    <>
      <header className="mb-14 flex flex-wrap items-center gap-x-4 gap-y-2 sm:mb-24"><Image src="/mattia.webp" alt="Mattia Ciuni" width={80} height={80} className="h-10 w-10 shrink-0 rounded-full object-cover" /><h1 className="m-0 font-serif text-lg font-semibold">Mattia Ciuni</h1><p className="m-0 w-full text-sm text-gray-1000 sm:w-auto sm:text-base">Founder &amp; CEO at <a href={site.payleUrl} rel="noopener noreferrer" className="font-semibold text-gray-1200">Payle</a></p></header>
      <div className="mb-16 space-y-6 text-text-paragraph sm:mb-24"><MilanClock className="text-gray-1000" /><p className="m-0">{text.homeLead} <a href={site.payleUrl} rel="noopener noreferrer" className="article-underline">Payle</a>. {text.homeBody}</p><p className="m-0">{home.whoBody2}</p><p className="m-0">{locale === "it" ? "Pubblico il lavoro con test di accettazione rigorosi e scelgo le persone per gli artefatti, non per i titoli. Scrivimi a " : locale === "fr" ? "Je publie le travail avec des tests d'acceptation rigoureux et je choisis les personnes pour leurs artefacts, pas leurs titres. Écrivez-moi à " : locale === "es" ? "Publico el trabajo con pruebas de aceptación rigurosas y elijo a las personas por sus artefactos, no por sus títulos. Escríbeme a " : locale === "de" ? "Ich veröffentliche Arbeit mit strengen Abnahmetests und wähle Menschen nach ihren Artefakten, nicht nach Titeln. Schreib mir an " : "I ship code under strict acceptance tests and hire on artifacts, not titles. Reach me at "}<CopyEmail />.</p></div>
      <section aria-labelledby="localized-about" className="mb-16 sm:mb-24"><h2 id="localized-about" className="mb-4 font-serif font-medium">{home.who}</h2><p className="m-0 text-text-paragraph">{home.whoBody}</p><p className="mt-4 m-0 text-text-paragraph">{home.whoBody2}</p></section>
      <section aria-labelledby="localized-principles" className="mb-16 sm:mb-24"><h2 id="localized-principles" className="mb-4 font-serif font-medium">{home.principles}</h2><ul className="m-0 list-disc space-y-5 pl-5">{home.principleItems.map(([title, body]) => <li key={title}><p className="m-0 font-serif italic">{title}</p><p className="m-0 text-gray-1000">{body}</p></li>)}</ul></section>
      <section aria-labelledby="localized-now" className="mb-16 sm:mb-24"><h2 id="localized-now" className="mb-4 font-serif font-medium">{home.now}</h2><p className="m-0 text-text-paragraph">{home.nowBody}</p></section>
      <section aria-labelledby="localized-projects" className="mb-16 sm:mb-24"><h2 id="localized-projects" className="mb-2 font-serif font-medium">{home.projects}</h2><ul className="m-0 list-none divide-y divide-gray-300 p-0"><li><a href={site.payleUrl} rel="noopener noreferrer" className="group grid min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-baseline gap-3 py-3.5"><span className="font-medium">Payle</span><span className="text-gray-1000">{home.payle}</span><ChevronRight className="h-4 w-4 self-center text-gray-1000" /></a></li><li><Link href={`/${locale}/thoughts/`} className="group grid min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-baseline gap-3 py-3.5"><span className="font-medium">{text.thoughts}</span><span className="text-gray-1000">{home.payleBody}</span><ChevronRight className="h-4 w-4 self-center text-gray-1000" /></Link></li></ul></section>
      <section aria-labelledby="localized-thoughts" className="mb-16 sm:mb-24"><h2 id="localized-thoughts" className="mb-2 font-serif font-medium">{text.thoughts}</h2><p className="mb-6 max-w-[600px] text-text-paragraph">{home.thoughtsBody}</p><ul className="m-0 list-none divide-y divide-gray-300 p-0">{posts.map((post) => <li key={post.slug}><Link href={`/${locale}/thoughts/${post.slug}/`}
 className="group flex min-w-0 flex-col items-start gap-1.5 py-3.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-4"><span className="min-w-0 font-serif font-[450]">{post.title}</span><span className="flex items-center gap-2 text-sm text-gray-1000">{post.category}<ChevronRight className="h-4 w-4" /></span></Link></li>)}</ul></section>
      <section aria-labelledby="localized-notes" className="mb-16 sm:mb-24"><div className="mb-2 flex flex-wrap items-baseline justify-between gap-4"><h2 id="localized-notes" className="font-serif font-medium">{text.notes}</h2><Link href={`/${locale}/notes/`} className="text-sm text-gray-1000">{ui.allNotes}</Link></div><p className="mb-6 max-w-[600px] text-text-paragraph">{home.notesBody}</p><ul className="m-0 list-none divide-y divide-gray-300 p-0">{notes.slice(0, 5).map((note) => <li key={note.slug}><Link href={`/${locale}/notes/${note.slug}/`}
 className="group flex flex-wrap items-baseline justify-between gap-4 py-3.5"><span className="font-serif">{note.title}</span><span className="text-sm text-gray-1000">{note.date}<ChevronRight className="ml-2 inline h-4 w-4" /></span></Link></li>)}</ul></section>
      <section aria-labelledby="localized-feedback" className="mb-16 sm:mb-24"><div className="mb-2 flex flex-wrap items-baseline justify-between gap-4"><h2 id="localized-feedback" className="font-serif font-medium">{text.feedback}</h2><Link href={`/${locale}/feedback/`} className="text-sm text-gray-1000">{ui.allFeedback}</Link></div><p className="mb-6 max-w-[600px] text-text-paragraph">{home.feedbackBody}</p><ul className="m-0 list-none rounded-3xl bg-gray-100 p-0">{feedback.map((item) => <li key={item.slug}><Link href={`/${locale}/feedback/${item.slug}/`}
 className="group flex min-w-0 flex-wrap items-baseline justify-between gap-4 px-5 py-4"><span className="font-serif font-[450]">{item.title}</span><span className="flex items-center gap-2 text-sm text-gray-1000">{item.author}<ChevronRight className="h-4 w-4" /></span></Link></li>)}</ul><div className="mt-6"><FeedbackModalButton label={text.sendFeedback} locale={locale} /></div></section>
      <section aria-labelledby="localized-newsletter" className="mb-16 sm:mb-24"><h2 id="localized-newsletter" className="mb-2 font-serif font-medium">{text.newsletter}</h2><p className="mb-5 max-w-[600px] text-text-paragraph">{locale === "it" ? "Una email a settimana: cosa ho spedito, cosa si è rotto, cosa ho deciso e perché." : locale === "fr" ? "Un e-mail par semaine : ce que j'ai livré, cassé, décidé et pourquoi." : locale === "es" ? "Un email a la semana: lo que lancé, lo que falló, lo que decidí y por qué." : locale === "de" ? "Eine E-Mail pro Woche: was ich gebaut, kaputt gemacht und entschieden habe und warum." : "One email a week: what I shipped, what broke, what I decided and why."}</p><NewsletterSection locale={locale} /></section>
      <section aria-labelledby="localized-field-notes" className="mb-16 sm:mb-24"><div className="mb-2 flex flex-wrap items-baseline justify-between gap-4"><h2 id="localized-field-notes" className="font-serif font-medium">{home.fieldNotes}</h2><span className="text-sm text-gray-1000">{ui.inProgress}</span></div><p className="mb-6 max-w-[600px] text-text-paragraph">{home.fieldBody}</p><div className="grid gap-4 sm:grid-cols-2"><Link href={`/${locale}/voice-notes/`} className="group border-t border-gray-300 pt-4"><span className="font-serif text-2xl">{home.voice}</span><p className="mt-2 text-sm leading-relaxed text-gray-1000">{home.voiceBody}</p></Link><Link href={`/${locale}/videos/`} className="group border-t border-gray-300 pt-4"><span className="font-serif text-2xl">{home.videos}</span><p className="mt-2 text-sm leading-relaxed text-gray-1000">{home.videosBody}</p></Link></div></section>
    </>
  );
}

export default async function LocalizedSectionRoute({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale: raw, slug } = await params;
  if (!isLocale(raw) || !SECTIONS.includes(slug as Section)) notFound();
  return <div lang={raw}><LocalizedSection locale={raw as Locale} section={slug as Section} /></div>;
}
