import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { posts } from "../lib/posts.ts";
import { notes } from "../lib/notes.ts";
import { feedback } from "../lib/feedback.ts";
import { jobs } from "../lib/careers/jobs-public.ts";
import { voiceNotes } from "../lib/voice-notes.ts";
import { founderVideos } from "../lib/videos.ts";
import { cmsPages } from "../lib/cms-pages.ts";
import { cmsRedirects } from "../lib/cms-redirects.ts";
import { cmsSiteSettings } from "../lib/cms-settings.ts";
import { blocksToMarkdown } from "../lib/cms-format.ts";

/**
 * Il catalogo che il pannello mostra al primo accesso, costruito dagli stessi
 * registry da cui legge la build. Serve a una cosa precisa: senza di questo
 * l'editor si aprirebbe vuoto e sembrerebbe che il pannello abbia perso il sito,
 * mentre il contenuto e' semplicamente in codice. Ogni voce qui e' un draft
 * modificabile: pubblicarla crea il file JSON che da quel momento vince sul
 * registry, e si puo' tornare indietro cancellando il file.
 */
const items = [
  ...posts.map((item) => ({ id: `seed-post-${item.slug}`, kind: "post", slug: item.slug, status: "published", title: item.title, description: item.description, body_markdown: blocksToMarkdown(item.content), data: { ...item, content: undefined } })),
  ...notes.map((item) => ({ id: `seed-note-${item.slug}`, kind: "note", slug: item.slug, status: "published", title: item.title, description: item.description, body_markdown: blocksToMarkdown(item.content), data: { ...item, content: undefined } })),
  ...feedback.map((item) => ({ id: `seed-feedback-${item.slug}`, kind: "feedback", slug: item.slug, status: "published", title: item.title, description: item.description, body_markdown: blocksToMarkdown(item.content), data: { ...item, content: undefined } })),
  ...jobs.map((item) => ({ id: `seed-job-${item.slug}`, kind: "job", slug: item.slug, status: "published", title: item.title, description: item.shortPitch, body_markdown: item.description, data: { ...item } })),
  ...voiceNotes.map((item) => ({ id: `seed-voice-${item.slug}`, kind: "voice_note", slug: item.slug, status: "published", title: item.title, description: item.description, body_markdown: "", data: { ...item, content: undefined } })),
  ...founderVideos.map((item) => ({ id: `seed-video-${item.slug}`, kind: "video", slug: item.slug, status: "published", title: item.title, description: item.description, body_markdown: "", data: { ...item, content: undefined } })),
  ...cmsPages.map((item) => ({ id: `seed-page-${item.slug}`, kind: "page", slug: item.slug, status: "published", title: item.title, description: item.description || "", body_markdown: blocksToMarkdown(item.content), data: { ...item, content: undefined } })),
  ...cmsRedirects.map((item) => ({ id: `seed-redirect-${item.slug}`, kind: "redirect", slug: String(item.slug), status: "published", title: `${item.from} → ${item.to}`, description: `Redirect ${item.status}`, body_markdown: "", data: { from: item.from, to: item.to, status: item.status, enabled: true } })),
  ...(Object.keys(cmsSiteSettings()).length
    ? [{ id: "seed-settings-site", kind: "settings", slug: "site", status: "published", title: "Site settings", description: "Name, role, description, contact and social profiles", body_markdown: "", data: { ...cmsSiteSettings() } }]
    : []),
];

const output = `// Generated by scripts/gen-cms-seed.mts. Do not edit by hand.\nimport type { AdminContentItem } from "../cms-types";\nexport const cmsSeedContent: AdminContentItem[] = ${JSON.stringify(items, null, 2)};\n`;
const destination = join(process.cwd(), "lib", "generated", "cms-seed.ts");
mkdirSync(join(process.cwd(), "lib", "generated"), { recursive: true });
let previous = "";
try {
  previous = readFileSync(destination, "utf8");
} catch {
  previous = "";
}
if (previous !== output) writeFileSync(destination, output);
console.log(`cms-seed: ${items.length} existing public entries available in admin`);
