-- Mattia Ciuni website
-- Owned copy of the site measurement
--
-- Run this file once in Supabase Dashboard -> SQL Editor, after
-- 20260922_000001_initial_schema.sql and 20260922_000002_private_kv.sql.
-- It contains no credentials and is safe to rerun.
--
-- Why this table exists: Umami and Google Analytics are two services someone
-- else runs. They can change a plan, prune history or disappear, and the
-- measurement of the site would go with them. The site therefore keeps its own
-- copy, written by `functions/api/collect.ts` on every event.
--
-- What is NOT in here, by design:
--   * no IP address, not even truncated, and none is derivable from anything
--     stored (the raw address is used for one hash and then dropped)
--   * no cookie, no device identifier, no user agent
--   * no `visitor_day` that survives the day: it is a truncated hash of the
--     address plus a server secret plus the UTC date, so it counts distinct
--     visits for one day and cannot link one day to the next, nor be reversed
--   * no personal data from the other forms (that lives in its own tables)
--
-- Access is server-side only with the service role. RLS is enabled with no
-- public policies: the anon key cannot read a single row.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default timezone('utc', now()),
  occurred_at timestamptz not null,
  event text not null,
  page_path text not null default '/',
  content_kind text not null default 'other',
  from_path text not null default '(entry)',
  next_page text not null default '',
  country text not null default '',
  device text not null default '',
  referrer_domain text not null default '',
  visitor_day text not null default '',
  params jsonb not null default '{}'::jsonb,
  constraint analytics_event_name check (char_length(event) between 1 and 64),
  constraint analytics_page_path check (char_length(page_path) between 1 and 300),
  constraint analytics_content_kind check (char_length(content_kind) between 1 and 40),
  constraint analytics_country check (char_length(country) <= 8),
  constraint analytics_device check (char_length(device) <= 24)
);

-- Le tre letture che servono davvero: "cosa succede in questi giorni", "come va
-- questo evento", "come va questa pagina". Un indice per ciascuna.
create index if not exists analytics_events_occurred_idx
  on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_event_idx
  on public.analytics_events (event, occurred_at desc);
create index if not exists analytics_events_page_idx
  on public.analytics_events (page_path, occurred_at desc);
create index if not exists analytics_events_visitor_idx
  on public.analytics_events (visitor_day, occurred_at desc);

alter table public.analytics_events enable row level security;

comment on table public.analytics_events is
  'Site-owned copy of the measurement: anonymous, no IP, no identifier that survives the day. Never exposed to the browser.';
comment on column public.analytics_events.visitor_day is
  'Truncated hash of (address + server secret + UTC date). Counts distinct visits for one day, links nothing across days, cannot be reversed.';
comment on column public.analytics_events.params is
  'Event-specific values, primitives only. The collector rejects nested objects and truncates every string.';

-- Letture aggregate, senza dover ricordare la forma dei dati ogni volta.
create or replace view public.analytics_daily
with (security_invoker = true) as
select
  date_trunc('day', occurred_at) as day,
  event,
  count(*) as events,
  count(distinct visitor_day) as visitors,
  count(distinct page_path) as pages
from public.analytics_events
group by 1, 2;

comment on view public.analytics_daily is
  'One row per day and event: volume, distinct daily visitors, how many pages were involved.';

-- Lettura per pagina: quante volte è stata aperta, quanto ci si è fermati, quanto
-- in basso si è arrivati. Il tempo e la profondità arrivano dall'evento
-- `page_leave`, quindi si leggono qui e non su `page_view`.
create or replace view public.analytics_pages
with (security_invoker = true) as
select
  page_path,
  content_kind,
  count(*) filter (where event = 'page_view') as views,
  count(*) filter (where event = 'page_leave') as leaves,
  round(avg((params ->> 'dwell_seconds')::numeric) filter (where event = 'page_leave'), 1) as avg_seconds,
  round(avg((params ->> 'max_scroll_percent')::numeric) filter (where event = 'page_leave'), 1) as avg_scroll_percent,
  max(occurred_at) as last_seen
from public.analytics_events
group by 1, 2;

comment on view public.analytics_pages is
  'Per page: views, sessions that left from it, average time and average scroll depth.';

-- Dove si va dopo: la coppia da-a presa direttamente dall'evento di uscita.
create or replace view public.analytics_flow
with (security_invoker = true) as
select
  page_path as from_path,
  next_page,
  count(*) as moves,
  round(avg((params ->> 'dwell_seconds')::numeric), 1) as avg_seconds_before_leaving
from public.analytics_events
where event = 'page_leave' and next_page <> ''
group by 1, 2;

comment on view public.analytics_flow is
  'Page-to-page movement: where a visit goes after each page, with the time spent before leaving.';

-- Nessuna scadenza e nessuna cancellazione automatica: questa copia esiste perché
-- i dati non si perdano. La pulizia, se mai servisse, è una decisione esplicita.
