-- Mattia Ciuni website
-- Initial Supabase schema
--
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- It contains no credentials and is safe to rerun.
-- The application accesses these tables only server-side with the service role.
-- RLS is enabled with no public policies by design.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.feedback_submissions (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  submitted_at timestamptz not null default timezone('utc', now()),
  status text not null default 'pending_review'
    check (status in ('pending_review', 'published', 'rejected')),
  name text not null default '',
  email text not null default '',
  message text not null,
  page_url text not null default '/',
  is_test boolean not null default false,
  notification_status text not null default 'not_configured'
    check (notification_status in ('sent', 'failed', 'not_configured')),
  notification_provider text,
  published_at timestamptz,
  rejected_at timestamptz,
  reject_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint feedback_message_length check (char_length(message) between 20 and 4000),
  constraint feedback_name_length check (char_length(name) <= 80),
  constraint feedback_email_length check (char_length(email) <= 254),
  constraint feedback_page_url_length check (char_length(page_url) between 1 and 300)
);

create index if not exists feedback_submissions_status_submitted_idx
  on public.feedback_submissions (status, submitted_at desc);
create index if not exists feedback_submissions_submitted_idx
  on public.feedback_submissions (submitted_at desc);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  canonical_email text not null unique,
  status text not null default 'subscribed'
    check (status in ('subscribed', 'unsubscribed', 'suppressed')),
  source text not null default 'direct',
  medium text not null default 'none',
  campaign text not null default '',
  content text not null default '',
  term text not null default '',
  landing_page text not null default '/',
  referrer text not null default '',
  subscribed_at timestamptz not null default timezone('utc', now()),
  unsubscribed_at timestamptz,
  last_seen_at timestamptz not null default timezone('utc', now()),
  brevo_contact_id text,
  beehiiv_subscription_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint newsletter_email_length check (char_length(email) between 3 and 254),
  constraint newsletter_canonical_email_length check (char_length(canonical_email) between 3 and 254)
);

create index if not exists newsletter_subscribers_status_idx
  on public.newsletter_subscribers (status, subscribed_at desc);
create index if not exists newsletter_subscribers_email_idx
  on public.newsletter_subscribers (email);

create table if not exists public.admin_sessions (
  id text primary key,
  role text not null check (role in ('ceo', 'cofounder')),
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default timezone('utc', now()),
  revoked_at timestamptz
);

create index if not exists admin_sessions_active_idx
  on public.admin_sessions (expires_at)
  where revoked_at is null;

create table if not exists public.admin_rate_limits (
  key text primary key,
  attempts integer not null default 0 check (attempts >= 0),
  window_started_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

create index if not exists admin_rate_limits_expires_idx
  on public.admin_rate_limits (expires_at);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_role text not null check (actor_role in ('ceo', 'cofounder', 'system')),
  action text not null,
  target_type text,
  target_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_type, target_id);

create table if not exists public.email_delivery_events (
  id bigint generated by default as identity primary key,
  provider text not null check (provider in ('resend', 'brevo', 'beehiiv', 'supabase')),
  purpose text not null check (purpose in ('newsletter_welcome', 'feedback_notification', 'feedback_confirmation')),
  recipient_hash text not null,
  related_feedback_id uuid references public.feedback_submissions(id) on delete set null,
  idempotency_key text unique,
  status text not null check (status in ('sent', 'failed', 'skipped')),
  provider_message_id text,
  error_code text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists email_delivery_events_feedback_idx
  on public.email_delivery_events (related_feedback_id, created_at desc);
create index if not exists email_delivery_events_recipient_idx
  on public.email_delivery_events (recipient_hash, purpose, created_at desc);

-- Keep updated_at server-generated for all mutable business tables.
drop trigger if exists feedback_submissions_set_updated_at on public.feedback_submissions;
create trigger feedback_submissions_set_updated_at
before update on public.feedback_submissions
for each row execute function public.set_updated_at();

drop trigger if exists newsletter_subscribers_set_updated_at on public.newsletter_subscribers;
create trigger newsletter_subscribers_set_updated_at
before update on public.newsletter_subscribers
for each row execute function public.set_updated_at();

-- No browser or anon client may read or write these tables. The service-role
-- key used by Pages Functions bypasses RLS, while the anon key cannot.
alter table public.feedback_submissions enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_rate_limits enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.email_delivery_events enable row level security;

comment on table public.feedback_submissions is 'Feedback received through the public site and its moderation state.';
comment on table public.newsletter_subscribers is 'One canonical subscriber identity per person/provider-safe email identity.';
comment on table public.admin_sessions is 'Short-lived admin sessions. Never store admin tokens here.';
comment on table public.admin_rate_limits is 'Server-side rate-limit counters.';
comment on table public.admin_audit_log is 'Minimal moderation and authentication audit trail. Never store secrets or message bodies.';
comment on table public.email_delivery_events is 'Delivery metadata only. Never store API keys or full message bodies.';
